# .travis.yml

language: node_js                                    
node_js:
- 12
env:
  global:
  - SKIP_PREFLIGHT_CHECK: true
before_install:
- npm install -g npm
script:
- npm install
- npm run test
- npm run build